export default {
  mainTitle: 'المباريات القادمة',
  noUpcoming: 'لا توجد مباريات قادمة',
  noMatchesThisDay: 'لا توجد مباريات في هذا اليوم',
  loadPast: 'عرض المباريات السابقة',
  pastMainTitle: 'المباريات السابقة',
  noPast: 'لا توجد مباريات سابقة',
  noPlayers: 'لا يوجد لاعبين',
  //facilities
  water: 'مياه شرب',
  cafeteria: 'كافتيريا',
  locker: 'خزانة',
  shower: 'دش',
  toilet: 'مرحاض',
  parking: 'موقف سيارات',
  //event
  eventEndedButton: 'انتهت المباراة',
  leaveEventButton: 'مغادرة المباراة',
  joinWaitingListButton: 'انضم إلى قائمة الانتظار',
  joinEventButton: 'انضم إلى المباراة',
  confirmJoinWaitingList: 'تأكيد الانضمام إلى قائمة الانتظار',
  confirmJoinWaitingListMsg: 'سيتم إعلامك عندما يغادر أحد اللاعبين مكانه.',
  confirmJoinWaitingListSuccessMsg: 'لقد انضممت بنجاح إلى قائمة الانتظار',
  confirmJoinWaitingListSuccessMsg2:
    'سيتم إعلامك عندما يغادر أحد اللاعبين مكانه.',
  confirmJoinEvent: 'تأكيد الانضمام',
  confirmJoinEventMsg: 'من خلال الانضمام إلى هذه المباراة، سيتم محاسبتك',
  confirmJoinEventSuccessMsg: 'لقد انضممت بنجاح إلى المباراة',
  confirmJoinEventSuccessMsg2Pt1: 'لا تنس أن المباراة ستبدأ في تمام',
  confirmJoinEventSuccessMsg2Pt2: 'لذا كن موجودًا في الوقت المحدد!',
  confirmLeaveEvent: 'تأكيد المغادرة',
  confirmLeaveEventMsg: 'هل أنت متأكد أنك تريد مغادرة هذه المباراة؟',
  confirmLeaveEventSuccessMsg: 'لقد غادرت المباراة بنجاح',
  registrationOpenSoon:
    'سيتم فتح التسجيل قبل يوم واحد من بدء المباراة في الساعة 1 مساءً!',

  pitchTypeLabel: 'نوع الملعب',
  outdoor: 'خارجي',
  indoor: 'داخلي',
  genderLabel: 'الجنس',
  male: 'ذكر',
  female: 'أنثى',
  mix: 'مختلط',
  priceLabel: 'السعر',
  durationLabel: 'المدة',
  durationMinutes: 'دقائق',
  durationHours: 'ساعات',
  ageLabel: 'العمر',
  playersLabel: 'اللاعبين',
  playerLabel: 'اللاعب',
  playersFull: 'مكتمل',
  backToMatchDetails: 'العودة إلى تفاصيل المباراة',
  directionsLabel: 'الاتجاهات',
  facilitiesLabel: 'المرافق',
  cityLabel: 'المدينة',
  viewOnMapLabel: 'عرض على خرائط Google',
  showOnMapLabel: 'عرض على الخريطة',
  addGuestsLabel: 'إضافة ضيوف',
  alertAddingGust: 'موجود بالفعل في المباراة، يرجى اختيار ضيف آخر',
  alertSelectGuests: 'يُسمح بضيفين فقط',
  confirmLabel: 'تأكيد',
  walletLabel: 'المحفظة',
  payment: 'فشل الدفع',
  paymentConfirm: 'تأكيد الدفع',
  paymentConfirmDesc: 'اختر طريقة الدفع',
  alertPaymentConfirmPt1: 'هل أنت متأكد أنك تريد خصم',
  alertPaymentConfirmPt2: 'من',
  yesConfirmButton: 'نعم، تأكيد',
  walletNotFound: 'المحفظة غير موجودة',
  alertWalletNotFoundPt1: 'اللاعب',
  alertWalletNotFoundPt2: 'لم يقم بإنشاء محفظة بعد.',
  payButton: 'دفع',
  cashButton: 'نقدًا',
  cashExchange: 'نقداً مع إعادة الباقي إلى المحفظة',

  leaveButton: 'مغادرة',
  doneButton: 'تم',

  cashPaid: 'دفع نقدًا',
  walletPaid: 'خصم من المحفظة',
  returnToWallet: 'الباقي (رصيد الى المحفظة)',

  addLabel: 'إضافة',
  removePlayerLabel: 'إزالة اللاعب',
  removeButton: 'إزالة',
  alertRemovePlayerPt1: 'هل أنت متأكد أنك تريد إزالة',
  alertRemovePlayerPt2: '؟',

  alertUndoPaymentTitle: 'فشل إلغاء الدفع',
  alertUndoPaymentDesc:
    'قام اللاعب بالدفع باستخدام الائتمان، يرجى الاتصال بالمشرف.',
  alertUserAbsent: 'اللاعب غائب',

  joinGKMsgPt1: 'الانضمام كحارس مرمى - احصل على',
  joinGKMsgPt2: '% خصم',

  warningLabel: 'تحذير',
  warningMsg:
    'ستبدأ المباراة في أقل من 4 ساعات، إذا غادرت المباراة الآن، ستواجه عقوبة الحظر لمدة 48 ساعة.',

  expensesLabel: 'المصروفات',
  noDataFound: 'لا توجد بيانات',
  staffExpenses: 'مصروفات الفريق',
  pitchExpenses: 'مصروفات الملعب',
  refereeLabel: 'الحكم',
  organizerLabel: 'المنظم',
  pitchLabel: 'الملعب',
  waterLabel: 'الماء',
  otherExpensesLabel: 'مصروفات أخرى',
  otherExpensesDesc: 'وصف المصروفات الأخرى',

  enterRefereeExpenses: 'أدخل مصروفات الحكم',
  enterOrganizerExpenses: 'أدخل مصروفات المنظم',
  enterPitchExpenses: 'أدخل مصروفات الملعب',
  enterWaterExpenses: 'أدخل مصروفات الماء',
  enterOtherExpenses: 'أدخل مصروفات الأخرى',
  enterOtherExpensesDescription: 'صف المصروفات الأخرى',

  submitExpenses: 'إرسال المصروفات',

  rosterTabLabel: 'القائمة',
  paymentTabLabel: 'المدفوعات',
  detailsButton: 'تفاصيل',
  revokeButton: 'إلغاء',
  chargeButton: 'دفع',
  onlineButton: 'اونلاين',

  matchSummaryLabel: 'ملخص المباراة',
  sendMatchSummary: 'إرسال ملخص المباراة',

  availableLabel: 'متاح',
  photoAlbumLabel: 'البوم الصور',
};
