export default {
  discover: 'اكتشف مجتمعك في كرة القدم',
  footballCommunity: 'مجتمع كرة القدم',
  findPlayersAround: 'ابحث عن لاعبين ومباريات حولك',
  registerButton: 'التسجيل',
  signInButton: 'تسجيل الدخول',
  signUpButton: 'التسجيل',
  createAccountButton: 'إنشاء حساب',
  continueGuest: 'متابعة كضيف',
  alertAlreadyInUsePt1: 'البريد الإلكتروني',
  alertAlreadyInUsePt2: 'مسجل بالفعل.',
  alertNotValid: 'ليس بريدًا إلكترونيًا صالحًا.',
  emailAddress: 'عنوان البريد الإلكتروني',
  emailDesc: 'ستحتاجه لتسجيل الدخول إلى التطبيق',
  emailOTPNote: 'ستتلقى رمزًا للتحقق.',
  alertOTPIncorrect: 'رمز التحقق غير صحيح',
  noCodeNote: 'لم تتلق الرمز؟',
  sendAgainCounterPt1: 'إعادة الإرسال في',
  sendAgainCounterPt2: 'ثواني',
  sendNowButton: 'إرسال الآن',
  enterCodeTitle: 'أدخل الرمز',
  enterCodeDesc: 'أدخل الرمز المكون من ستة أرقام الذي تم إرساله لك في',
  alertPasswordLimit: 'يجب أن تتكون كلمة المرور من 6 أحرف على الأقل.',
  alertPasswordSpecialChar:
    'يجب أن تحتوي كلمة المرور على حرف كبير ورقم وحرف خاص',
  alertNoMatchPasswords: 'كلمة المرور وتأكيد كلمة المرور غير متطابقين.',
  newPasswordTitle: 'إنشاء كلمة مرور',
  newPasswordDesc: 'ستحتاجها لتسجيل الدخول إلى التطبيق',
  newPasswordPlaceholder: 'كلمة المرور الجديدة',
  confirmPasswordPlaceholder: 'تأكيد كلمة المرور',
  newUsernameTitle: 'إنشاء اسم المستخدم',
  newUsernameDesc: 'هذا هو الاسم الذي سيراه الناس علنيًا',
  usernamePlaceholder: 'اسم المستخدم',
  alertEmptyName: 'الرجاء إدخال اسم',
  newNameTitle: 'اسمك',
  newNameDesc: 'أدخل اسمك حتى نتمكن من معاملتك بشكل مناسب',
  contactNumberTitle: 'رقم الاتصال الخاص بك',
  contactNumberPleaceholder: 'رقم الاتصال',
  emerContactNumberPleaceholder: 'رقم الاتصال للطوارئ',
  emerContactNumberDesc: '(أول شخص ذوي الصلة أو من يرعاك)',
};
